# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Test
      run: |
        go install github.com/ory/go-acc@v0.2.8
        go-acc -o coverage.out ./...

    - name: barrelman
      run: |
        git fetch origin $GITHUB_BASE_REF
        go run cmd/barrelman/main.go coverage.out <(git diff origin/$GITHUB_BASE_REF)
